spring:
  application:
    name: wohnung-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: employees
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee?currentSchema=employees
    username: root
    password: example
  bot:
    name: WohnungServiceBot
    token: 7187221848:AAEDP5OGaUXzW49m8m7Q7vkrqxwxaMti7PE
